Repository WeblateOrg/weblate, pull requests merged in 2021-08, with the labels that each got.

#6087 Sentence splicing removed. Filemask.
  weblate/templates/trans/alert/nomaskmatches.html
Labels: wontfix

#5895 Docs: Glossary spelling "Untranslatable strings"
  docs/user/glossary.rst
Labels: documentation

#6457 Translations update from Weblate
  weblate/locale/ms/LC_MESSAGES/django.po
Labels: automerge

#6488 Translations update from Weblate
  weblate/locale/de/LC_MESSAGES/django.po
Labels: automerge
